### ISSUE TITLE
Setup domain name

### ISSUE THREAD

**Issue by ponch-alfonso** [ponch-alfonso/ph-lotto-results#23]
## Tasks

- [x] Buy [domain name](https://www.namecheap.com/domains/registration/results/?domain=pcso-lotto-results): 
  - pcso-lotto-results.com
  - pcso-draw-results.com
  - pcso-results.com
- [x] Setup with Firebase 
- [x] Add to [reCaptcha](https://www.google.com/recaptcha/admin/site/694989243/settings):

**Comment by ponch-alfonso** [comment]
bought www.pcso-lotto.com

**Comment by ponch-alfonso** [comment]
![image](https://github.com/ponch-alfonso/ph-lotto-results/assets/26197407/cf0cfc55-6516-40ef-b76f-4c96111fd5f5)

Canonical domain is pcso-lotto.com
