### ISSUE TITLE
More cleanups 

### ISSUE THREAD

**Issue by ponch-alfonso** [ponch-alfonso/ph-lotto-results#24]
## Tasks

- [x] Check names
- [x] Fix sharing link
  - Read about link previews
  - Meta tags
  - Should show:
    - Some images, lotto results, current dates
- [x] Add app icons
- [ ] ~~Improve about us text~~ - #32
